### ISSUE TITLE
Lock creation is not safe

### ISSUE THREAD

**Issue by dpaneda** [chriscannon/highlander#2]
The acquire of the lock is not safe enough, as some race condition can cause more than one process to acquire the lock.

The problem resides on have two steps on the lock. That means, it's not one atomic operation. The usual way to create this kind of lock is to create a directory. Check this link for more information, in this case is about bash scripting but the issue is exactly the same.

http://wiki.bash-hackers.org/howto/mutex

**Comment by chriscannon** [comment]
Folder creation is a great idea! I'll implement that in my next release.

**Comment by untitaker** [comment]
Might as well use [lockfile](https://pypi.python.org/pypi/lockfile/)?

**Comment by dpaneda** [comment]
Seems good at first sight but using that implementation will make harder to detect locks from dead process (right now the PID is used for that).

**Comment by harlowja** [comment]
Use https://fasteners.readthedocs.org/en/0.9.0/api/process_lock.html then...

**Comment by chriscannon** [comment]
Fasteners is a little more complicated because he also deals with multiple locks, which would be overkill here. I do see he does create a directory as dpaneda suggested, so I'm just going to quickly implement that for Highlander.

**Comment by chriscannon** [comment]
I made a pull request #4 to address this problem. Please let me know if you have any feedback.

**Comment by dpaneda** [comment]
There are still some race conditions on the code, due to the deleting of stale locks. The

I suggest you refactor the logic a bit and follow this steps to acquire a lock:
 * Check if there is any lock active and remove if the folder creation time is too old or the process is no longer running.
 * If there is no lock, try to create the folder
 * If the folder is properly created, you have the lock. Create the pid file and whenever other file you want to create inside the folder.
 * If not, another instance of the process win. So just do whatever you do when the acquire fails

**Comment by chriscannon** [comment]
I see why this is the best method now. The last check is the creation of the directory, which we know is atomic. Thanks for the clarification Daniel!

**Comment by dpaneda** [comment]
Yes, that's the idea. The clean of stale locks just require some caution because some other process could be also doing the same thing, but is not the critical part, because two process cleaning at the same time is not really a problem. Two process acquiring the lock is the real problem, which will be impossible to occur with this implementation.

**Comment by chriscannon** [comment]
I still need to write tests, but check out the latest commit.

**Comment by chriscannon** [comment]
And tests are now in place (easier than I thought).

**Comment by chriscannon** [comment]
I'm going to go ahead and merge PR #4. It's at least better than what's currently in master.
