### ISSUE TITLE
Celery integration

### ISSUE THREAD

**Issue by jdotjdot** [chriscannon/highlander#3]
Has this been tested with [Celery](http://celery.readthedocs.org/en/latest/index.html)?  I could see it working out of the box, but since my understanding is Celery does some complicated things with child processes, I'd want to make sure that it doesn't have any unexpected side effects before throwing this intro production.

**Comment by chriscannon** [comment]
It hasn't, but if you do try it out please let me know the results.

**Comment by chriscannon** [comment]
I have decided not to support Celery.
